var k=true,m=null,o=false;
(function(b){b.a.r=function(a){function f(){function c(){if(!s++){l.detachEvent?l.detachEvent("onload",c):l.removeEventListener("load",c,o);var a=k;try{if(r)throw"timeout";var e,g;g=l.contentWindow?l.contentWindow.document:l.contentDocument?l.contentDocument:l.document;j.responseText=g.body?g.body.innerHTML:m;j.responseXML=g.XMLDocument?g.XMLDocument:g;j.getResponseHeader=function(a){return{"content-type":d.dataType}[a]};if(d.dataType=="json"||d.dataType=="script"){var h=g.getElementsByTagName("textarea")[0];
j.responseText=h?h.value:j.responseText}else if(d.dataType=="xml"&&!j.responseXML&&j.responseText!=m)j.responseXML=f(j.responseText);e=b.L(j,d.dataType)}catch(t){a=o,b.handleError(d,j,"error",t)}a&&(d.i(e,"success"),n&&b.event.c("ajaxSuccess",[j,d]));n&&b.event.c("ajaxComplete",[j,d]);n&&!--b.p&&b.event.c("ajaxStop");d.complete&&d.complete(j,a?"success":"error");setTimeout(function(){i.remove();j.responseXML=m},100)}}function f(a){var b;window.ActiveXObject?(b=new ActiveXObject("Microsoft.XMLDOM"),
b.async="false",b.loadXML(a)):b=(new DOMParser).parseFromString(a,"text/xml");return b&&b.documentElement&&b.documentElement.tagName!="parsererror"?b:m}var e=h[0],d=b.extend({},b.F,a),g="jqFormIO"+(new Date).getTime(),i=b('<iframe id="'+g+'" name="'+g+'" />'),l=i[0],u=b.j.opera&&window.opera.version()<9;if(b.j.w||u)l.src='javascript:false;document.write("");';i.H({position:"absolute",top:"-1000px",left:"-1000px"});var j={responseText:m,responseXML:m,status:0,statusText:"n/a",getAllResponseHeaders:function(){},
getResponseHeader:function(){},setRequestHeader:function(){}},n=d.global;n&&!b.p++&&b.event.c("ajaxStart");n&&b.event.c("ajaxSend",[j,d]);var s=0,r=0;setTimeout(function(){var f=h.d("target"),j=h.d("action");h.d({target:g,encoding:"multipart/form-data",enctype:"multipart/form-data",method:"POST",action:d.url});d.timeout&&setTimeout(function(){r=k;c()},d.timeout);var n=[];try{if(a.k)for(var p in a.k)n.push(b('<input type="hidden" name="'+p+'" value="'+a.k[p]+'" />').s(e)[0]);i.s("body");l.attachEvent?
l.attachEvent("onload",c):l.addEventListener("load",c,o);e.submit()}finally{h.d("action",j),f?h.d("target",f):h.O("target"),b(n).remove()}},10)}typeof a=="function"&&(a={i:a});var a=b.extend({url:this.d("action")||window.location.toString(),type:this.d("method")||"GET"},a||{}),c={};this.c("form-pre-serialize",[this,a,c]);if(!c.B){var e=this.m(a.Q);if(a.data){a.k=a.data;for(var d in a.data)e.push({name:d,value:a.data[d]})}if(!(a.t&&a.t(e,this,a)===o)&&(this.c("form-submit-validate",[e,this,a,c]),!c.B)){c=
b.n(e);a.type.toUpperCase()=="GET"?(a.url+=(a.url.indexOf("?")>=0?"&":"?")+c,a.data=m):a.data=c;var h=this,g=[];a.o&&g.push(function(){h.o()});a.l&&g.push(function(){h.l()});if(!a.dataType&&a.target){var i=a.i||function(){};g.push(function(c){b(a.target).K(c).b(i,arguments)})}else a.i&&g.push(a.i);a.i=function(a,b){for(var c=0,d=g.length;c<d;c++)g[c](a,b,h)};c=b("input:file",this).h();e=o;for(d=0;d<c.length;d++)c[d]&&(e=k);a.M||e?b.j.P&&a.v?b.get(a.v,f):f():b.C(a);this.c("form-submit-notify",[this,
a])}}};b.a.D=function(a){return this.q().bind("submit.form-plugin",function(){b(this).r(a);return o}).b(function(){b(":submit,input:image",this).bind("click.form-plugin",function(a){var c=this.form;c.e=this;if(this.type=="image")if(a.offsetX!=void 0)c.f=a.offsetX,c.g=a.offsetY;else if(typeof b.a.z=="function"){var e=b(this).z();c.f=a.pageX-e.left;c.g=a.pageY-e.top}else c.f=a.pageX-this.offsetLeft,c.g=a.pageY-this.offsetTop;setTimeout(function(){c.e=c.f=c.g=m},10)})})};b.a.q=function(){this.A("submit.form-plugin");
return this.b(function(){b(":submit,input:image",this).A("click.form-plugin")})};b.a.m=function(a){var f=[];if(this.length==0)return f;var c=this[0],e=a?c.getElementsByTagName("*"):c.elements;if(!e)return f;for(var d=0,h=e.length;d<h;d++){var g=e[d],i=g.name;if(i)if(a&&c.e&&g.type=="image")!g.disabled&&c.e==g&&f.push({name:i+".x",value:c.f},{name:i+".y",value:c.g});else if((g=b.h(g,k))&&g.constructor==Array)for(var q=0,p=g.length;q<p;q++)f.push({name:i,value:g[q]});else g!==m&&typeof g!="undefined"&&
f.push({name:i,value:g})}if(!a&&c.e){a=c.getElementsByTagName("input");d=0;for(h=a.length;d<h;d++)e=a[d],(i=e.name)&&!e.disabled&&e.type=="image"&&c.e==e&&f.push({name:i+".x",value:c.f},{name:i+".y",value:c.g})}return f};b.a.J=function(a){return b.n(this.m(a))};b.a.I=function(a){var f=[];this.b(function(){var c=this.name;if(c){var e=b.h(this,a);if(e&&e.constructor==Array)for(var d=0,h=e.length;d<h;d++)f.push({name:c,value:e[d]});else e!==m&&typeof e!="undefined"&&f.push({name:this.name,value:e})}});
return b.n(f)};b.a.h=function(a){for(var f=[],c=0,e=this.length;c<e;c++){var d=b.h(this[c],a);d===m||typeof d=="undefined"||d.constructor==Array&&!d.length||(d.constructor==Array?b.N(f,d):f.push(d))}return f};b.h=function(a,f){var c=a.name,e=a.type,d=a.tagName.toLowerCase();typeof f=="undefined"&&(f=k);if(f&&(!c||a.disabled||e=="reset"||e=="button"||(e=="checkbox"||e=="radio")&&!a.checked||(e=="submit"||e=="image")&&a.form&&a.form.e!=a||d=="select"&&a.selectedIndex==-1))return m;if(d=="select"){var h=
a.selectedIndex;if(h<0)return m;for(var c=[],d=a.options,g=(e=e=="select-one")?h+1:d.length,h=e?h:0;h<g;h++){var i=d[h];if(i.selected){i=b.j.w&&!i.attributes.value.specified?i.text:i.value;if(e)return i;c.push(i)}}return c}return a.value};b.a.l=function(){return this.b(function(){b("input,select,textarea",this).u()})};b.a.u=b.a.G=function(){return this.b(function(){var a=this.type,b=this.tagName.toLowerCase();if(a=="text"||a=="password"||b=="textarea")this.value="";else if(a=="checkbox"||a=="radio")this.checked=
o;else if(b=="select")this.selectedIndex=-1})};b.a.o=function(){return this.b(function(){(typeof this.reset=="function"||typeof this.reset=="object"&&!this.reset.nodeType)&&this.reset()})};b.a.enable=function(a){a==void 0&&(a=k);return this.b(function(){this.disabled=!a})};b.a.select=function(a){a==void 0&&(a=k);return this.b(function(){var f=this.type;if(f=="checkbox"||f=="radio")this.checked=a;else if(this.tagName.toLowerCase()=="option")f=b(this).parent("select"),a&&f[0]&&f[0].type=="select-one"&&
f.find("option").select(o),this.selected=a})}})(jQuery);